apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: activepieces-ingress
  namespace: activepieces
  labels:
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`activepieces.{{ .Values.cloudflare_zone }}`)
      kind: Rule
      services:
        - name: activepieces
          port: 80
  tls:
    domains:
    - main: {{ .Values.cloudflare_zone }}
      sans:
      - activepieces.{{ .Values.cloudflare_zone }}
    secretName: {{ .Values.cloudflare_zone_hyphen }}-tls
