apiVersion: v1
kind: Service
metadata:
  name: activepieces
  namespace: activepieces
spec:
  selector:
    app: activepieces
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
